# -*- coding: utf-8 -*-
"""app_cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYSHBe2rShxWGNrn6OAGh5Wk1Vgaw0ZE
"""

"""Libraries"""

import streamlit as st
from sentence_transformers import SentenceTransformer, util
import openai
import os
import tempfile

# OpenAI (optional bonus feature)
#openai.api_key = st.secrets.get(api_key, os.getenv(api_key))

# App UI
st.title("Candidate Recommendation Engine")
st.markdown("Upload resumes and input a job description. Get the top-matching candidates.")

# Job description input
job_description = st.text_area("Job Description", height=200)

# Resume file upload
uploaded_files = st.file_uploader("Upload Candidate Resumes (TXT or PDF)", type=["txt", "pdf"], accept_multiple_files=True)

# Optional: max candidates to return
top_k = st.slider("Show Top K Candidates", min_value=1, max_value=10, value=5)

# Helper: extract text from file
def extract_text(file):
    if file.type == "application/pdf":
        from PyPDF2 import PdfReader
        pdf = PdfReader(file)
        return "\n".join([page.extract_text() or "" for page in pdf.pages])
    else:
        return file.read().decode("utf-8", errors="ignore")
